"""Runtime configuration for the EnvScaler service."""

import os


MAX_CONCURRENT_ENVS = int(os.environ.get("OPENENV_ENVSCALER_MAX_CONCURRENT_ENVS", "256"))
WORKER_START_TIMEOUT = float(os.environ.get("OPENENV_ENVSCALER_START_TIMEOUT", "30"))
TOOL_CALL_TIMEOUT = float(os.environ.get("OPENENV_ENVSCALER_TOOL_TIMEOUT", "30"))
VERIFY_TIMEOUT = float(os.environ.get("OPENENV_ENVSCALER_VERIFY_TIMEOUT", "120"))
WORKER_MEMORY_LIMIT_MB = int(os.environ.get("OPENENV_ENVSCALER_WORKER_MEMORY_MB", "4096"))
MAX_TOOL_RESULT_CHARS = int(os.environ.get("OPENENV_ENVSCALER_MAX_TOOL_RESULT_CHARS", "200000"))
MAX_VERIFY_DETAILS = int(os.environ.get("OPENENV_ENVSCALER_MAX_VERIFY_DETAILS", "20"))
