models:
  "memory_selector_lora":
    api_type: "openai"
    base_url: "http://127.0.0.1:8000/v1"
    model: your_model_name
    api_key: "EMPTY"
    temperature: 0.2
    top_p: 1

  "memory_writer_lora":
    api_type: "openai"
    base_url: "http://127.0.0.1:8000/v1"
    model: your_model_name
    api_key: "EMPTY"
    temperature: 0.2
    top_p: 1
